spring:
  datasource:
    url: jdbc:mysql://localhost:3306/securitydb
    username: root
    password: root
    
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
    
server:
  port: 4568
  
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761